# Generated by Django 3.0.1 on 2020-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('area_land', models.IntegerField(blank=True, null=True)),
                ('area_water', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_growth', models.TextField(blank=True, null=True)),
                ('birth_rate', models.TextField(blank=True, null=True)),
                ('death_rate', models.TextField(blank=True, null=True)),
                ('migration_rate', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facts',
                'managed': False,
            },
        ),
    ]
